"use client";
import { useEffect, useMemo, useState } from "react";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
type Row={sku:string;name:string;stock:number;sales7:number;sales14:number;sales30:number;sales60:number};
const n=new Intl.NumberFormat("pt-BR",{maximumFractionDigits:0}),d=new Intl.NumberFormat("pt-BR",{maximumFractionDigits:1});
export default function Page(){
 const [period,setPeriod]=useState<7|14|30|60>(30),[mode,setMode]=useState<"conservador"|"intenso">("conservador"),[data,setData]=useState<{asOf:string|null;rows:Row[]}>({asOf:null,rows:[]});
 useEffect(()=>{fetch("/api/reposicao-full").then(r=>r.json()).then(setData)},[]);
 const rows=useMemo(()=>data.rows.map(r=>{const sales=period===7?r.sales7:period===14?r.sales14:period===30?r.sales30:r.sales60,base=sales/period,recent=r.sales7/7,v=mode==="intenso"?base*.45+recent*.55:Math.min(base,recent||base),target=mode==="intenso"?45:30,coverage=v?r.stock/v:null,send=Math.max(0,Math.ceil(v*target-r.stock)),risk=coverage===null?"Sem venda":coverage<7?"Crítico":coverage<14?"Alto":coverage<target?"Atenção":"Coberto";return{...r,sales,v,coverage,send,risk}}).filter(r=>r.send>0).sort((a,b)=>b.send-a.send),[data,mode,period]);
 return <main className="flex flex-col gap-5"><div><h1 className="text-3xl font-semibold tracking-tight">Reposição FULL</h1><p className="text-muted-foreground text-sm">Envio sugerido pelas vendas até {data.asOf??"—"}.</p></div><div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle>Período</CardTitle></CardHeader><CardContent className="flex gap-2">{([7,14,30,60] as const).map(x=><button key={x} onClick={()=>setPeriod(x)} className={`rounded-md px-3 py-2 text-sm ${period===x?"bg-primary text-primary-foreground":"bg-muted"}`}>{x} dias</button>)}</CardContent></Card><Card><CardHeader><CardTitle>Estratégia</CardTitle><CardDescription>Intenso dá mais peso às vendas recentes.</CardDescription></CardHeader><CardContent className="flex gap-2">{(["conservador","intenso"] as const).map(x=><button key={x} onClick={()=>setMode(x)} className={`rounded-md px-3 py-2 text-sm capitalize ${mode===x?"bg-primary text-primary-foreground":"bg-muted"}`}>{x}</button>)}</CardContent></Card></div><div className="grid gap-4 sm:grid-cols-3"><Card><CardHeader><CardDescription>SKUs para enviar</CardDescription><CardTitle>{n.format(rows.length)}</CardTitle></CardHeader></Card><Card><CardHeader><CardDescription>Unidades recomendadas</CardDescription><CardTitle>{n.format(rows.reduce((s,r)=>s+r.send,0))}</CardTitle></CardHeader></Card><Card><CardHeader><CardDescription>Críticos</CardDescription><CardTitle>{n.format(rows.filter(r=>r.risk==="Crítico").length)}</CardTitle></CardHeader></Card></div><Card><CardHeader><CardTitle>Envio recomendado</CardTitle><CardDescription>Meta de cobertura: {mode==="intenso"?45:30} dias.</CardDescription></CardHeader><CardContent className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Risco</TableHead><TableHead>SKU</TableHead><TableHead>Produto</TableHead><TableHead className="text-right">FULL</TableHead><TableHead className="text-right">Vendas</TableHead><TableHead className="text-right">Média/dia</TableHead><TableHead className="text-right">Cobertura</TableHead><TableHead className="text-right">Enviar</TableHead></TableRow></TableHeader><TableBody>{rows.map(r=><TableRow key={r.sku}><TableCell><Badge variant={r.risk==="Crítico"?"destructive":r.risk==="Alto"?"default":"secondary"}>{r.risk}</Badge></TableCell><TableCell>{r.sku}</TableCell><TableCell>{r.name}</TableCell><TableCell className="text-right">{n.format(r.stock)}</TableCell><TableCell className="text-right">{n.format(r.sales)}</TableCell><TableCell className="text-right">{d.format(r.v)}</TableCell><TableCell className="text-right">{r.coverage===null?"—":d.format(r.coverage)+" d"}</TableCell><TableCell className="text-right font-semibold">{n.format(r.send)}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card></main>
}
