import { AlertCircle } from "lucide-react";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { CurveDataTables } from "./_components/curve-data-tables";
import { loadAbcdeDashboard, loadProductPeriodComparison } from "./_lib/load-abcde-dashboard";
function month(value: string | null) { return value ? new Intl.DateTimeFormat("pt-BR", { month: "long", year: "numeric" }).format(new Date(`${value}T12:00:00`)) : "—"; }
export default async function Page() {
  try {
    const [data, comparison7, comparison30] = await Promise.all([loadAbcdeDashboard(), loadProductPeriodComparison(7), loadProductPeriodComparison(30)]);
    if (!data || data.rows.length === 0) return <Alert><AlertCircle /><AlertTitle>Sem dados de performance</AlertTitle><AlertDescription>Importe relatórios de desempenho para montar a Curva ABCDE.</AlertDescription></Alert>;
    return <main className="flex flex-col gap-5"><div className="flex flex-col gap-1"><p className="font-medium text-primary text-xs uppercase tracking-[0.18em]">Classificação por faturamento</p><h1 className="text-3xl font-semibold tracking-tight">Curva ABCDE</h1><p className="text-muted-foreground text-sm">Compare {month(data.currentMonth)} com {month(data.previousMonth)}. A queda de curva aparece diretamente como A → C.</p></div>{!data.hasPreviousMonth ? <Alert><AlertCircle /><AlertTitle>Ainda não há mês anterior</AlertTitle><AlertDescription>A Curva atual já está calculada. Importe a performance do mês anterior para exibir as mudanças de curva.</AlertDescription></Alert> : null}<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Card><CardHeader className="pb-2"><CardDescription>Produtos analisados</CardDescription><CardTitle className="text-2xl tabular-nums">{data.summary.products}</CardTitle></CardHeader><CardContent className="text-muted-foreground text-xs">Com visitas, vendas ou faturamento</CardContent></Card><Card className="border-red-200"><CardHeader className="pb-2"><CardDescription>Caíram de curva</CardDescription><CardTitle className="text-2xl tabular-nums text-red-600">{data.summary.dropped}</CardTitle></CardHeader><CardContent className="text-muted-foreground text-xs">Ex.: Curva A → Curva C</CardContent></Card><Card className="border-emerald-200"><CardHeader className="pb-2"><CardDescription>Subiram de curva</CardDescription><CardTitle className="text-2xl tabular-nums text-emerald-600">{data.summary.improved}</CardTitle></CardHeader><CardContent className="text-muted-foreground text-xs">Ganharam participação no faturamento</CardContent></Card><Card><CardHeader className="pb-2"><CardDescription>Mantiveram a curva</CardDescription><CardTitle className="text-2xl tabular-nums">{data.summary.stable}</CardTitle></CardHeader><CardContent className="text-muted-foreground text-xs">Mesmo grupo no mês anterior</CardContent></Card></div><CurveDataTables curveData={data} comparison7={comparison7} comparison30={comparison30} /></main>;
  } catch (error) { return <Alert variant="destructive"><AlertCircle /><AlertTitle>Não foi possível carregar a Curva ABCDE</AlertTitle><AlertDescription>{error instanceof Error ? error.message : "Ocorreu um erro ao consultar os dados."}</AlertDescription></Alert>; }
}
