import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import type { PerformanceDashboardData, PerformancePeriod, PerformanceRow } from "../_lib/load-performance-dashboard";

const integer = new Intl.NumberFormat("pt-BR", { maximumFractionDigits: 0 });
const currency = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });
const percent = new Intl.NumberFormat("pt-BR", { style: "percent", maximumFractionDigits: 1 });
const date = (value: string | null) => value ? value.split("-").reverse().join("/") : "—";
const percentage = (value: number | null | undefined) => percent.format(Number(value ?? 0));

function PeriodCard({ title, period }: { title: string; period: PerformancePeriod | null }) {
  return <Card><CardHeader><CardDescription>{title}</CardDescription><CardTitle>{period ? `${integer.format(period.visits)} visitas` : "Sem histórico completo"}</CardTitle></CardHeader><CardContent className="text-sm">{period ? <div className="flex flex-col gap-1"><span>{integer.format(period.sales)} vendas · {integer.format(period.units)} unidades</span><span>{currency.format(period.grossSales)} · conversão {percentage(period.conversion)}</span><span className="text-muted-foreground text-xs">{date(period.start)} até {date(period.end)}</span></div> : "É necessário ter todos os dias do período importados."}</CardContent></Card>;
}
function Ranking({ title, description, rows }: { title: string; description: string; rows: PerformanceRow[] }) {
  return <Card><CardHeader><CardTitle>{title}</CardTitle><CardDescription>{description}</CardDescription></CardHeader><CardContent className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>SKU / MLB</TableHead><TableHead className="text-right">Visitas</TableHead><TableHead className="text-right">Vendas</TableHead><TableHead className="text-right">Conversão</TableHead></TableRow></TableHeader><TableBody>{rows.slice(0, 10).map((row, index) => <TableRow key={`${row.sku ?? "sem-sku"}-${row.mlb ?? index}`}><TableCell><div className="font-medium">{row.sku ?? "Sem SKU"}</div><div className="text-muted-foreground text-xs">{row.mlb ?? "MLB não informado"}{row.productName ? ` · ${row.productName}` : ""}</div></TableCell><TableCell className="text-right tabular-nums">{integer.format(row.visits)}</TableCell><TableCell className="text-right tabular-nums">{integer.format(row.sales)}</TableCell><TableCell className="text-right tabular-nums">{percentage(row.conversion)}</TableCell></TableRow>)}</TableBody></Table>{rows.length === 0 ? <p className="text-muted-foreground text-sm">Nenhum anúncio encontrado.</p> : null}</CardContent></Card>;
}
export function PerformanceDashboard({ data }: { data: PerformanceDashboardData }) {
  const latest = data.latestDay;
  return <div className="flex flex-col gap-5"><div><h1 className="text-3xl font-semibold tracking-tight">Performance</h1><p className="text-muted-foreground text-sm">Visitas, conversão e vendas dos anúncios com dados importados.</p></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Card><CardHeader className="pb-2"><CardDescription>Visitas</CardDescription><CardTitle className="text-2xl tabular-nums">{integer.format(latest.visits ?? 0)}</CardTitle></CardHeader><CardContent className="text-muted-foreground text-xs">{date(latest.date)}</CardContent></Card><Card><CardHeader className="pb-2"><CardDescription>Vendas</CardDescription><CardTitle className="text-2xl tabular-nums">{integer.format(latest.sales ?? 0)}</CardTitle></CardHeader></Card><Card><CardHeader className="pb-2"><CardDescription>Unidades</CardDescription><CardTitle className="text-2xl tabular-nums">{integer.format(latest.units ?? 0)}</CardTitle></CardHeader></Card><Card><CardHeader className="pb-2"><CardDescription>Conversão</CardDescription><CardTitle className="text-2xl tabular-nums">{percentage(latest.conversion)}</CardTitle></CardHeader></Card><Card><CardHeader className="pb-2"><CardDescription>Faturamento bruto</CardDescription><CardTitle className="text-2xl tabular-nums">{currency.format(latest.grossSales ?? 0)}</CardTitle></CardHeader></Card></div><div className="grid gap-4 lg:grid-cols-2"><PeriodCard title="Últimos 7 dias" period={data.periods.last7}/><PeriodCard title="7 dias anteriores" period={data.periods.previous7}/></div><div className="grid gap-4 xl:grid-cols-3"><Ranking title="Mais visitas" description="Anúncios com maior exposição." rows={data.topVisits}/><Ranking title="Muitas visitas e baixa conversão" description="Oportunidades para revisar preço, capa ou descrição." rows={data.lowConversion}/><Ranking title="Visitas sem venda" description="Anúncios que receberam tráfego, mas não converteram." rows={data.visitsWithoutSales}/></div></div>;
}
